name: CI Unit Tests

on:
  pull_request:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.19"
          enable-cache: true

      - name: Install pytesseract
        run: sudo apt-get update && sudo apt-get install -y tesseract-ocr tesseract-ocr-spa

      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest
