name: Lint (ruff)

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - feature/**
      - release/**
      - hotfix/**

# From ruff documentation: https://docs.astral.sh/ruff/integrations/#github-actions
jobs:
  ruff:
    runs-on: ubuntu-latest

    # Needed for commiting changes: https://github.com/stefanzweifel/git-auto-commit-action
    permissions:
        contents: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.19"
          enable-cache: true

      - name: Install project
        run: uv sync --locked --all-extras --dev

      - name: Run Ruff check
        run: uv run ruff check .

      - name: Run Ruff format check
        run: uv run ruff format --check .
